services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db:/app/db
      - ./lib:/app/lib
      - ./public:/app/public
      - ./public/assets:/app/public/assets
      - ./test:/app/test
      - ./tmp:/app/tmp
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432
    depends_on:
      - db

volumes:
  postgres_data:
  bundle:
